In [1]:
n =0
while n < 10
    n+=1
    println(n)
end

1
2
3
4
5
6
7
8
9
10


In [2]:
myfriends = ["Ted", "Robyn", "Barney", "Lily","Marshall"]
i =1
while i< length(myfriends)
    friend = myfriends[i]
    println("Hi $friend, it's great to see you!")
    i+=1
end

Hi Ted, it's great to see you!
Hi Robyn, it's great to see you!
Hi Barney, it's great to see you!
Hi Lily, it's great to see you!


In [3]:
for friend in myfriends
       println("Hi $friend, it's great to see you!")
end

Hi Ted, it's great to see you!
Hi Robyn, it's great to see you!
Hi Barney, it's great to see you!
Hi Lily, it's great to see you!
Hi Marshall, it's great to see you!


In [5]:
for n in  1:2:10
    println(n)
end

1
3
5
7
9


In [7]:
m, n = 5,5 
A= fill(0, (m,n))
# формирование массива, в котором значение каждой записи
# является суммой индексов строки и столбца:
for i in 1 :m
    for j in 1:n
        A[i,j] =i+j
    end
end
A


5×5 Array{Int64,2}:
 2  3  4  5   6
 3  4  5  6   7
 4  5  6  7   8
 5  6  7  8   9
 6  7  8  9  10

In [9]:
B = fill(0, m,n)

for i in 1: m, j in 1:n
    B[i,j]  =i+j
end
B

5×5 Array{Int64,2}:
 2  3  4  5   6
 3  4  5  6   7
 4  5  6  7   8
 5  6  7  8   9
 6  7  8  9  10

In [10]:
C = [i+j for i in 1:m, j in 1:n]
C

5×5 Array{Int64,2}:
 2  3  4  5   6
 3  4  5  6   7
 4  5  6  7   8
 5  6  7  8   9
 6  7  8  9  10

In [11]:
N = 6
# формирование массива, в котором значение каждой записи
# является суммой индексов строки и столбца:

if ((N % 3 == 0) && (N % 5 == 0))
    println("FizzBuzz")
elseif N % 3 == 0
    println("Fizz")
elseif N%5==0
    println("Buzz")
else
    prinln(N)
end

Fizz


In [17]:
x = 5
y =10
(x > y) ? x : y

10

In [18]:
function sayhi(name)
    println("Hi $name, it's great to see you !")
end

sayhi (generic function with 1 method)

In [19]:
sayhi("C-3PO")

Hi C-3PO, it's great to see you !


In [22]:
function f(x)
    x^2
end

f (generic function with 1 method)

In [23]:
f(42)

1764

In [25]:
sayhi(name)  = println("Hi $name, it's great to see you !")

sayhi (generic function with 1 method)

In [26]:
sayhi("C-3PO")

Hi C-3PO, it's great to see you !


In [27]:
f2(x) = x^2

f2 (generic function with 1 method)

In [35]:
f2(42)

1764

In [31]:
sayhi3 = name ->println("Hi $name, it's great to see you !")

#9 (generic function with 1 method)

In [32]:
f3 = x->x^2

#11 (generic function with 1 method)

In [33]:
sayhi("C-3PO")

Hi C-3PO, it's great to see you !


In [34]:
f3(42)

1764

In [36]:
#  задаём массив v:
v  = [3, 5, 2]
sort(v)
v

3-element Array{Int64,1}:
 3
 5
 2

In [37]:
sort!(v)
v

3-element Array{Int64,1}:
 2
 3
 5

In [38]:
map(f, [1,2,3])

3-element Array{Int64,1}:
 1
 4
 9

In [41]:
[f(3) ...]

1-element Array{Int64,1}:
 9

In [42]:
map(x->x^3, [1,2,3])

3-element Array{Int64,1}:
  1
  8
 27

In [43]:
f(x) = x^2
broadcast(f, [1,2,3])

3-element Array{Int64,1}:
 1
 4
 9

In [44]:
f.([1,2,3])

3-element Array{Int64,1}:
 1
 4
 9

In [45]:
f.([2,3,4])

3-element Array{Int64,1}:
  4
  9
 16

In [50]:
# Задаём матрицу A:
A = [i + 3*j for j in 0:2, i in 1:3]

3×3 Array{Int64,2}:
 1  2  3
 4  5  6
 7  8  9

In [53]:
#  Вызываем функцию f возведения в квадрат
f(A)

3×3 Array{Int64,2}:
  30   36   42
  66   81   96
 102  126  150

In [54]:
B = f.(A)

3×3 Array{Int64,2}:
  1   4   9
 16  25  36
 49  64  81

In [55]:
@. A+2*f(A)/A

3×3 Array{Float64,2}:
  3.0   6.0   9.0
 12.0  15.0  18.0
 21.0  24.0  27.0

In [57]:
A .+2 .* f.(A) ./ A

3×3 Array{Float64,2}:
  3.0   6.0   9.0
 12.0  15.0  18.0
 21.0  24.0  27.0

In [58]:
broadcast(x-> x+2*f(x)/x, A)

3×3 Array{Float64,2}:
  3.0   6.0   9.0
 12.0  15.0  18.0
 21.0  24.0  27.0

In [59]:
import Pkg
Pkg.add("Colors")
using Colors

   Updating registry at `C:\Users\acers\.julia\registries\General`


   Updating git-repo `https://github.com/JuliaRegistries/General.git`


Fetching: [========================================>]  100.0 % %]  27.7 %>                         ]  36.9 % %Fetching: [=======================>                 ]  56.5 %              ]  64.6 %Fetching: [=============================>           ]  72.4 %]  87.9 %5 %

  Resolving package versions...
No Changes to `C:\Users\acers\.julia\environments\v1.5\Project.toml`
No Changes to `C:\Users\acers\.julia\environments\v1.5\Manifest.toml`


In [60]:
palette = distinguishable_colors(100)

In [61]:
rand(palette, 3,3 )

## Задания для самостоятельного выполнения


In [1]:
# – выведите на экран целые числа от 1 до 100 и напечатайте их квадраты;

for i in 1:100
    println(i, "", i^2)
end

11
24
39
416
525
636
749
864
981
10100
11121
12144
13169
14196
15225
16256
17289
18324
19361
20400
21441
22484
23529
24576
25625
26676
27729
28784
29841
30900
31961
321024
331089
341156
351225
361296
371369
381444
391521
401600
411681
421764
431849
441936
452025
462116
472209
482304
492401
502500
512601
522704
532809
542916
553025
563136
573249
583364
593481
603600
613721
623844
633969
644096
654225
664356
674489
684624
694761
704900
715041
725184
735329
745476
755625
765776
775929
786084
796241
806400
816561
826724
836889
847056
857225
867396
877569
887744
897921
908100
918281
928464
938649
948836
959025
969216
979409
989604
999801
10010000


In [2]:

#– создайте словарь squares, который будет содержать целые числа в качестве 
#ключей и квадраты в качестве их пар-значений;
squares = Dict(i=>i^2 for i=1:10)
for key in sort(collect(keys(squares)))
        println("$key => $(squares[key])")
end


1 => 1
2 => 4
3 => 9
4 => 16
5 => 25
6 => 36
7 => 49
8 => 64
9 => 81
10 => 100


In [3]:
# – создайте массив squares_arr, содержащий квадраты всех чисел от 1 до 100

squares_arr = [i^2 for i=1:100]

100-element Array{Int64,1}:
     1
     4
     9
    16
    25
    36
    49
    64
    81
   100
   121
   144
   169
     ⋮
  7921
  8100
  8281
  8464
  8649
  8836
  9025
  9216
  9409
  9604
  9801
 10000

In [4]:
#2. Напишите условный оператор, который печатает число, если число чётное, и строку
#«нечётное», если число нечётное. .
N=6 
if (N%2==0)
        println(N)
else
    println("Нечетное")
end

6


In [5]:
#Перепишите код, используя тернарный оператор
(N%2==0) ? println(N) : println("Нечетное")

6


In [6]:
#3 Напишите функцию add_one, которая добавляет 1 к своему входу.
add_one(x) = x+1

add_one (generic function with 1 method)

In [7]:
add_one(4)

5

In [8]:
#Пользуйте map() или broadcast() для задания матрицы 𝐴, каждый элемент которой 
#увеличивается на единицу по сравнению с предыдущим
m, n =5, 5
A= fill(0, (m,n))
map(x-> add_one(x), A)

5×5 Array{Int64,2}:
 1  1  1  1  1
 1  1  1  1  1
 1  1  1  1  1
 1  1  1  1  1
 1  1  1  1  1

In [10]:
# 5. Задайте матрицу 𝐴 следующего вида:
A = [1 1 3; 5 2 6; -2 -1 -3]

3×3 Array{Int64,2}:
  1   1   3
  5   2   6
 -2  -1  -3

In [11]:
# Найдите 𝐴3
A^3

3×3 Array{Int64,2}:
 0  0  0
 0  0  0
 0  0  0

In [12]:
A[:, 3] =A[:,1]+A[:,2]
A

3×3 Array{Int64,2}:
  1   1   2
  5   2   7
 -2  -1  -3

In [13]:
B= repeat([10 -10 10], 15)

15×3 Array{Int64,2}:
 10  -10  10
 10  -10  10
 10  -10  10
 10  -10  10
 10  -10  10
 10  -10  10
 10  -10  10
 10  -10  10
 10  -10  10
 10  -10  10
 10  -10  10
 10  -10  10
 10  -10  10
 10  -10  10
 10  -10  10

In [14]:
# Вычислите матрицу 𝐶 = 𝐵𝑇𝐵.
C = B'*B


3×3 Array{Int64,2}:
  1500  -1500   1500
 -1500   1500  -1500
  1500  -1500   1500

In [15]:
Z = zeros(6,6)

6×6 Array{Float64,2}:
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0

In [16]:
E= ones(6,6)

6×6 Array{Float64,2}:
 1.0  1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0  1.0

In [21]:
Z1 = zeros(6,6)
Z2 = zeros(6,6)
Z3 = zeros(6,6)
Z4 = zeros(6,6)
 for i in 1:6
    for j in 1:6
        if(i==j-1) || (i==j+1)
            Z1[i,j]=1
        end
        if(i==j) || (i==j+2) || (i==j-2)
            Z2[i,j] =1
        end
        if(i==5-j) || (i==7-j) || (i==9-j)
            Z3[i,j] =1
        end
        if(i+j)% 2==0
            Z4[i,j]=1
        end
    end
end

In [22]:
Z1

6×6 Array{Float64,2}:
 0.0  1.0  0.0  0.0  0.0  0.0
 1.0  0.0  1.0  0.0  0.0  0.0
 0.0  1.0  0.0  1.0  0.0  0.0
 0.0  0.0  1.0  0.0  1.0  0.0
 0.0  0.0  0.0  1.0  0.0  1.0
 0.0  0.0  0.0  0.0  1.0  0.0

In [23]:
Z2

6×6 Array{Float64,2}:
 1.0  0.0  1.0  0.0  0.0  0.0
 0.0  1.0  0.0  1.0  0.0  0.0
 1.0  0.0  1.0  0.0  1.0  0.0
 0.0  1.0  0.0  1.0  0.0  1.0
 0.0  0.0  1.0  0.0  1.0  0.0
 0.0  0.0  0.0  1.0  0.0  1.0

In [24]:
Z3

6×6 Array{Float64,2}:
 0.0  0.0  0.0  1.0  0.0  1.0
 0.0  0.0  1.0  0.0  1.0  0.0
 0.0  1.0  0.0  1.0  0.0  1.0
 1.0  0.0  1.0  0.0  1.0  0.0
 0.0  1.0  0.0  1.0  0.0  0.0
 1.0  0.0  1.0  0.0  0.0  0.0

In [25]:
Z4

6×6 Array{Float64,2}:
 1.0  0.0  1.0  0.0  1.0  0.0
 0.0  1.0  0.0  1.0  0.0  1.0
 1.0  0.0  1.0  0.0  1.0  0.0
 0.0  1.0  0.0  1.0  0.0  1.0
 1.0  0.0  1.0  0.0  1.0  0.0
 0.0  1.0  0.0  1.0  0.0  1.0

In [36]:
# 8 - . В языке R есть функция outer(). Фактически, это матричное умножение с возможностью изменить применяемую операцию (например, заменить произведение на
#сложение или возведение в степень).

function outer(X, Y, op)
if (ndims(X)==1)
X=reshape(X, (size(X,1), size(X,2)))
end
if (ndims(Y)==1)
Y=reshape(Y, (size(Y,1), size(Y,2)))
end
Z=zeros(size(X)[1], size(Y)[2])
for i in 1:size(X)[1], j in 1:size(Y)[2], k in size(X)[2]
Z[i, j] = op(X[i,k], Y[k,j])
end
return Z
end

outer (generic function with 1 method)

In [37]:
M1 = [i for i in 0:4]

5-element Array{Int64,1}:
 0
 1
 2
 3
 4

In [38]:
outer(M1, M1', +)

5×5 Array{Float64,2}:
 0.0  1.0  2.0  3.0  4.0
 1.0  2.0  3.0  4.0  5.0
 2.0  3.0  4.0  5.0  6.0
 3.0  4.0  5.0  6.0  7.0
 4.0  5.0  6.0  7.0  8.0

In [39]:
M2 =[i for i in 1:5]
outer(M1,M2', ^)

5×5 Array{Float64,2}:
 0.0   0.0   0.0    0.0     0.0
 1.0   1.0   1.0    1.0     1.0
 2.0   4.0   8.0   16.0    32.0
 3.0   9.0  27.0   81.0   243.0
 4.0  16.0  64.0  256.0  1024.0

In [42]:
outer(M1, M1', +).%5

5×5 Array{Float64,2}:
 0.0  1.0  2.0  3.0  4.0
 1.0  2.0  3.0  4.0  0.0
 2.0  3.0  4.0  0.0  1.0
 3.0  4.0  0.0  1.0  2.0
 4.0  0.0  1.0  2.0  3.0

In [44]:
outer([i for i in 0:9], [i for i in 0:9]', +).%10

10×10 Array{Float64,2}:
 0.0  1.0  2.0  3.0  4.0  5.0  6.0  7.0  8.0  9.0
 1.0  2.0  3.0  4.0  5.0  6.0  7.0  8.0  9.0  0.0
 2.0  3.0  4.0  5.0  6.0  7.0  8.0  9.0  0.0  1.0
 3.0  4.0  5.0  6.0  7.0  8.0  9.0  0.0  1.0  2.0
 4.0  5.0  6.0  7.0  8.0  9.0  0.0  1.0  2.0  3.0
 5.0  6.0  7.0  8.0  9.0  0.0  1.0  2.0  3.0  4.0
 6.0  7.0  8.0  9.0  0.0  1.0  2.0  3.0  4.0  5.0
 7.0  8.0  9.0  0.0  1.0  2.0  3.0  4.0  5.0  6.0
 8.0  9.0  0.0  1.0  2.0  3.0  4.0  5.0  6.0  7.0
 9.0  0.0  1.0  2.0  3.0  4.0  5.0  6.0  7.0  8.0

In [45]:
outer([i for i in 0:8], [i for i in -9:-1]', -).%9

9×9 Array{Float64,2}:
 0.0  8.0  7.0  6.0  5.0  4.0  3.0  2.0  1.0
 1.0  0.0  8.0  7.0  6.0  5.0  4.0  3.0  2.0
 2.0  1.0  0.0  8.0  7.0  6.0  5.0  4.0  3.0
 3.0  2.0  1.0  0.0  8.0  7.0  6.0  5.0  4.0
 4.0  3.0  2.0  1.0  0.0  8.0  7.0  6.0  5.0
 5.0  4.0  3.0  2.0  1.0  0.0  8.0  7.0  6.0
 6.0  5.0  4.0  3.0  2.0  1.0  0.0  8.0  7.0
 7.0  6.0  5.0  4.0  3.0  2.0  1.0  0.0  8.0
 8.0  7.0  6.0  5.0  4.0  3.0  2.0  1.0  0.0

In [46]:
# Решить систему
A = outer([i for i in 1:5], [i for i in 1:5]', -)
A = abs.(A)
A = A.+1
y= [7, -1, -3, 5, 17]
x= inv(A)*y


5-element Array{Float64,1}:
 -1.9999999999999996
  3.0
  5.0
  2.0
 -4.0

In [47]:
# Создайте матрицу 𝑀 размерности 6 × 10, элементами которой являются целые числа,
# выбранные случайным образом с повторениями из совокупности 1, 2, … , 10.
# Найдите число элементов в каждой строке матрицы 𝑀, которые больше числа 

M=  rand(1:10, 6, 10)

6×10 Array{Int64,2}:
 10  10   9  2  3   6   7  1   8   3
  1   3   1  3  6  10   4  2  10   2
  3   4   5  6  9   9  10  6   1   4
  2   8  10  5  2   3   9  8   1   3
  1   6   5  6  3   3   2  5   6  10
  7  10   2  7  7   4   9  5  10   2

In [51]:
N =4
for i in 1:6
    c=0
    for j in 1:10
        if M[i,j]>N
            c =c+1
        end
    end
    println(" line ", i, "contains ", c, " elements > ", N)
end

 line 1contains 6 elements > 4
 line 2contains 3 elements > 4
 line 3contains 6 elements > 4
 line 4contains 5 elements > 4
 line 5contains 6 elements > 4
 line 6contains 7 elements > 4


In [52]:
N =4
for i in 1:6
    c=0
    for j in 1:10
        if M[i,j]==N
            c =c+1
        end
    end
    if c==2
    println(" строка ", i, "содержит чило ", N, " ровно 2 раза ")
    end
end


 строка 3содержит чило4 ровно 2 раза 


In [57]:
K=75
sum=0
for j in 1:10
    for k in (j+1):10
        for i in 1:6
            sum =sum + M[i,j]+M[i,k]
        end
        if sum > K
            println(" Сумма столбцов ", j, " ", k, " = ", sum)
        end
        sum =0
    end
end

 Сумма столбцов 2 6 = 76
 Сумма столбцов 2 7 = 82
 Сумма столбцов 2 9 = 77
 Сумма столбцов 6 7 = 76
 Сумма столбцов 7 9 = 77


In [60]:
# вычислить сумму  
A = [(i^4)/(3+j) for j in 1:5, i in 1:20]
sum=0
for i in 1:5
    for j in 1:20
        sum =sum + A[i,j]
    end
end
sum

639215.2833333338

In [61]:
# вычислить сумму  
A = [(i^4)/(3+i*j) for j in 1:5, i in 1:20]
sum=0
for i in 1:5
    for j in 1:20
        sum =sum + A[i,j]
    end
end
sum

89912.02146097131